### ISSUE TITLE
Remote WebDriver error since Chrome 92 on Linux machines

### ISSUE THREAD

**Issue by tyge68** [bonigarcia/selenium-jupiter#188]
**Description of the problem**: Since recent Chrome 92 update (few days now), we observed many failures when it tries to execute our Selenium Jupiter based ITs.

**Browser and version**: Chrome in Docker version 92

**Operating system**: Linux (Centos RHEL 7 3.10.0-1160.11.1.el7.x86_64)  

**Selenium-Jupiter version**: 3.4.0

**Selenium-Jupiter use**:
```
    @BeforeEach
    @SuppressFBWarnings
    public final void setUp(final WebDriver driver) {
        WebDriverRunner.setWebDriver(driver);
        driver.manage().window().maximize();
        if (!SelenideLogger.hasListener(LISTENER_NAME)) {
            SelenideLogger.addListener(LISTENER_NAME, this);
        }
    }
```

**Selenium-Jupiter traces**: 
```
Standard Output
06:49:33.088 [main] INFO  c.a.c.t.j.e.SlingClientExtension$Store - Building client for url=http://10.251.203.153:4502/cp user=admin
06:49:33.089 [main] WARN  i.g.b.seljup.SeleniumExtension - Browser list for context id [engine:junit-jupiter]/[class:com.boxing.cq.dam.cfm.it.selenium.tests.ContentFragmentEditorIT]/[method:testCreateVariation()] not found
06:49:33.092 [main] INFO  i.g.b.s.handler.DockerDriverHandler - Using CHROME version 92.0 (latest)
06:49:33.096 [main] INFO  i.g.bonigarcia.seljup.DockerService - Starting Docker container docker-hub-remote.dr-uw2.boxingitc.com/aerokube/selenoid:1.10.1
06:49:34.370 [main] WARN  i.g.b.seljup.SeleniumExtension - Exception closing webdriver object RemoteWebDriver: chrome on LINUX (null)
org.openqa.selenium.json.JsonException: Unable to determine type from: H. Last 1 characters read: H
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ip-10-251-203-153.corp.boxing.com', ip: '10.251.203.153', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.11.1.el7.x86_64', java.version: '11.0.12'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.json.JsonInput.peek(JsonInput.java:122)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$null$6(JsonTypeCoercer.java:140)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:126)
	at org.openqa.selenium.json.Json.toType(Json.java:69)
	at org.openqa.selenium.json.Json.toType(Json.java:55)
	at org.openqa.selenium.json.Json.toType(Json.java:50)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:87)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:609)
	at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:452)
	at io.github.bonigarcia.seljup.SeleniumExtension.conditionalQuitWebDriver(SeleniumExtension.java:511)
	at io.github.bonigarcia.seljup.SeleniumExtension.quitWebDriver(SeleniumExtension.java:503)
	at io.github.bonigarcia.seljup.SeleniumExtension.teardown(SeleniumExtension.java:458)
	at io.github.bonigarcia.seljup.SeleniumExtension.afterEach(SeleniumExtension.java:412)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAfterEachCallbacks$11(TestMethodTestDescriptor.java:255)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$12(TestMethodTestDescriptor.java:271)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$13(TestMethodTestDescriptor.java:271)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAllAfterMethodsOrCallbacks(TestMethodTestDescriptor.java:270)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAfterEachCallbacks(TestMethodTestDescriptor.java:254)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:143)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:127)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
06:49:34.972 [pool-28-thread-1] INFO  i.g.bonigarcia.seljup.DockerService - Stopping Docker container docker-hub-remote.dr-uw2.boxingitc.com/aerokube/selenoid:1.10.1
Standard Error
Jul 26, 2021 6:49:34 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
```
**Error trace**:

**Comment by tyge68** [comment]
Note if I force to return to version 91 with -Dsel.jup.default.version=91, the issue is not observed.
I wonder if that mean that with version 92 , we need to get the updated version of selenium java api which got updated currently on the "master" branch , but which is not yet released ?

**Comment by bonigarcia** [comment]
Indeed there is a problem starting with Chrome 92. More precisely, the cause of the problem in the underlying chromedriver 92, required to control Chromium-based browsers (such as Chrome or Edge). It causes several problems when it runs in a Docker container, just like in Selenium-Jupiter. I reported the problem in the [chromedriver issue tracker](https://bugs.chromium.org/p/chromedriver/issues/detail?id=3857), but there is no answer yet.

I manged to solve partially the problem in the master branch of Selenium-Jupiter. I am making an important evolution of Selenium-Jupiter these days. It will be available as Selenium-Jupiter 4 in the near future, but I am still working on it. Nevertheless, there is a public snapshot version, just in case you want to give a try. You need to bump the version to 4.0.0-SNAPSHOT and include the sonatype screenshots repository. You can see an example [here](https://github.com/bonigarcia/selenium-webdriver-java/tree/master/selenium-webdriver-junit5-seljup). You will need to bump to Selenium WebDriver 4 as well (BTW, in Selenium-Jupiter 4, WebDriver is not a transitive dependency anymore, so you need to explicitly declare it).

**Comment by tyge68** [comment]
@bonigarcia thanks for your inputs, on my side I have tried to update, then I quickly got blocked as our tests also use Selenide API, and Selenide API is currently not compatible with 4.0.0-beta-4 version of Selenium Java API. There is a PR on their side on that topic -> https://github.com/selenide/selenide/pull/1407 , so until that get fixed I will be able to retry with 4.0.0 snapshot from Selenium Jupiter.

**Comment by tyge68** [comment]
Status update: I see that https://bugs.chromium.org/p/chromedriver/issues/detail?id=3857 is fixed, it's not clear how long it take for that fix to be part of the next "latest" docker image for chrome, but let see, I will retry in a few day/week to see if that is definitely resolved.

**Comment by bonigarcia** [comment]
This should be fixed in Selenium-Jupiter 4.1.0, just released.
