### ISSUE TITLE
SeleniumJupiter extension hang while trying to stop docker container

### ISSUE THREAD

**Issue by tyge68** [bonigarcia/selenium-jupiter#200]
**Description of the problem**: I am trying to upgrade to latest selenium-jupiter library using 4.0.1 release, but each time I run my junit test that uses the extension  it now hang while trying to stop the docker container

**Browser and version**:  docker chrome 95

**Operating system**: Mac OS 11.6

**Selenium-Jupiter version**: 4.0.1

**Selenium-Jupiter use**: 

**Selenium-Jupiter traces**:
15:25:57.096 [main] INFO  c.a.q.s.m.MockedAEMServer - Before ALL
Warning: Nashorn engine is planned to be removed from a future JDK release
15:25:58.471 [main] INFO  i.g.b.w.d.DockerService - Starting Docker container selenoid/vnc:chrome_95.0
2021-10-27 15:26:01  org.openqa.selenium.remote.tracing.opentelemetry.OpenTelemetryTracer  INFO  Using OpenTelemetry for tracing 
2021-10-27 15:26:01  org.openqa.selenium.remote.ProtocolHandshake  INFO  Detected dialect: W3C 
15:26:01.994 [main] INFO  c.a.c.t.j.e.DingClientExtension$Store - Building client for url=http://localhost:5502/ user=admin
15:26:02.110 [main] INFO  c.a.q.s.UITest - subject=http://192.168.43.29:5502/libs/grommit/core/content/login.html element=open
15:26:02.222 [main] INFO  c.a.q.s.UITest - subject=http://192.168.43.29:5502/libs/grommit/core/content/login.html element=open duration=111 status=PASS error=null
15:26:02.224 [main] INFO  c.a.q.s.p.Helpers - waitNetworkIdled with polling interval=250ms
15:26:02.506 [main] INFO  c.a.q.s.p.Helpers - waitDocumentLoadCompleted
15:26:02.515 [main] INFO  c.a.q.s.p.c.CrabReady - waitCrabReady(body)
15:26:02.643 [main] INFO  c.a.q.s.p.Helpers - waitDOMIdled with polling interval=250ms
15:26:02.931 [main] INFO  c.a.q.s.UITest - subject=exists() element=#Crab-collection-id-0
15:26:02.981 [main] INFO  c.a.q.s.UITest - subject=exists() element=#Crab-collection-id-0 duration=50 status=PASS error=null
15:26:02.982 [main] INFO  c.a.q.s.UITest - subject=set value(admin) element=#username
15:26:03.108 [main] INFO  c.a.q.s.UITest - subject=set value(admin) element=#username duration=126 status=PASS error=null
15:26:03.108 [main] INFO  c.a.q.s.UITest - subject=set value(admin) element=#password
15:26:03.232 [main] INFO  c.a.q.s.UITest - subject=set value(admin) element=#password duration=124 status=PASS error=null
15:26:03.243 [main] INFO  c.a.q.s.UITest - subject=should be(can be clicked: visible and enabled) element=#submit-button
15:26:03.283 [main] INFO  c.a.q.s.UITest - subject=should be(can be clicked: visible and enabled) element=#submit-button duration=40 status=PASS error=null
15:26:04.541 [main] INFO  c.a.q.s.UITest - subject=should(exist) element=#submit-button
15:26:04.571 [main] INFO  c.a.q.s.UITest - subject=should(exist) element=#submit-button duration=29 status=PASS error=null
15:26:04.591 [Forwarding actions on session 3f175bc171d415a7f3c616c7201c23e3 to remote] INFO  c.a.q.s.UITest - subject=get wrapped element() element=#submit-button
15:26:04.604 [Forwarding actions on session 3f175bc171d415a7f3c616c7201c23e3 to remote] INFO  c.a.q.s.UITest - subject=get wrapped element() element=#submit-button duration=12 status=PASS error=null
15:26:04.791 [main] INFO  c.a.q.s.p.Helpers - waitNetworkIdled with polling interval=250ms
15:26:05.065 [main] INFO  c.a.q.s.p.Helpers - waitDocumentLoadCompleted
15:26:05.074 [main] INFO  c.a.q.s.p.c.CrabReady - waitCrabReady(body)
15:26:05.200 [main] INFO  c.a.q.s.p.Helpers - waitDOMIdled with polling interval=250ms
15:26:05.511 [main] INFO  c.a.q.s.UITest - subject=http://192.168.43.29:5502/editor.html/content/some/page.html element=open
15:26:05.671 [main] INFO  c.a.q.s.UITest - subject=http://192.168.43.29:5502/editor.html/content/some/page.html element=open duration=159 status=PASS error=null
15:26:05.671 [main] INFO  c.a.q.s.p.EditorPage - waitPageReady
15:26:05.682 [main] INFO  c.a.q.s.p.EditorPage - precondition checked
15:26:05.690 [main] INFO  c.a.q.s.p.EditorPage - pageReady checked
15:26:05.775 [main] INFO  c.a.q.s.u.Coverage - Coverage stored
15:26:05.785 [main] INFO  c.a.q.s.u.Coverage - Coverage stored
15:26:05.794 [main] INFO  c.a.q.s.j.e.JSCoverageExtension - LocalStorage JSCover detected, saved, then cleaned
15:26:05.828 [main] ERROR c.a.q.s.UITest - ================== BROWSER LOGS =======================
15:26:05.828 [main] ERROR c.a.q.s.UITest - [2021-10-27T13:26:02.246Z] [SEVERE] http://192.168.43.29:5502/favicon.ico - Failed to load resource: the server responded with a status of 404 (Not Found)
15:26:05.828 [main] ERROR c.a.q.s.UITest - [2021-10-27T13:26:05.584Z] [SEVERE] http://192.168.43.29:5502/tools/foundation/clientlibs/jquery.min.js - Failed to load resource: the server responded with a status of 404 (Not Found)
15:26:05.828 [main] ERROR c.a.q.s.UITest - [2021-10-27T13:26:05.584Z] [SEVERE] http://192.168.43.29:5502/tools/clientlibs/grommit/lawnchair.min.js - Failed to load resource: the server responded with a status of 404 (Not Found)
15:26:05.828 [main] ERROR c.a.q.s.UITest - [2021-10-27T13:26:05.586Z] [SEVERE] http://192.168.43.29:5502/tools/foundation/clientlibs/shared.min.js - Failed to load resource: the server responded with a status of 404 (Not Found)
15:26:05.828 [main] ERROR c.a.q.s.UITest - [2021-10-27T13:26:05.586Z] [SEVERE] http://192.168.43.29:5502/tools/clientlibs/grommit/Crabui2/optional/imageeditor.min.js - Failed to load resource: the server responded with a status of 404 (Not Found)
15:26:05.828 [main] ERROR c.a.q.s.UITest - [2021-10-27T13:26:05.587Z] [SEVERE] http://192.168.43.29:5502/libs/clientlibs/grommit/richtext.min.js - Failed to load resource: the server responded with a status of 404 (Not Found)
15:26:05.828 [main] ERROR c.a.q.s.UITest - [2021-10-27T13:26:05.590Z] [SEVERE] http://192.168.43.29:5502/libs/db/gui/components/authoring/editors/clientlibs/utils.min.js - Failed to load resource: the server responded with a status of 404 (Not Found)
15:26:05.828 [main] ERROR c.a.q.s.UITest - [2021-10-27T13:26:05.590Z] [SEVERE] http://192.168.43.29:5502/libs/grommit/ui/clientlibs/annotations.min.js - Failed to load resource: the server responded with a status of 404 (Not Found)
15:26:05.828 [main] ERROR c.a.q.s.UITest - [2021-10-27T13:26:05.591Z] [SEVERE] http://192.168.43.29:5502/libs/db/gui/components/authoring/editors/clientlibs/core.min.js - Failed to load resource: the server responded with a status of 404 (Not Found)
15:26:05.828 [main] ERROR c.a.q.s.UITest - [2021-10-27T13:26:05.594Z] [SEVERE] http://192.168.43.29:5502/libs/db/ups/rte/plugin.min.js - Failed to load resource: the server responded with a status of 404 (Not Found)
15:26:05.828 [main] ERROR c.a.q.s.UITest - [2021-10-27T13:26:05.594Z] [SEVERE] http://192.168.43.29:5502/libs/db/gui/components/authoring/searchfield/clientlibs/searchfield.min.js - Failed to load resource: the server responded with a status of 404 (Not Found)
15:26:05.828 [main] ERROR c.a.q.s.UITest - [2021-10-27T13:26:05.595Z] [SEVERE] http://192.168.43.29:5502/libs/db/contentinsight/clientlibs/editor.min.js - Failed to load resource: the server responded with a status of 404 (Not Found)
15:26:05.828 [main] ERROR c.a.q.s.UITest - [2021-10-27T13:26:05.613Z] [SEVERE] http://192.168.43.29:5502/tools/db/personalization/clientlib/underscore.min.js - Failed to load resource: the server responded with a status of 404 (Not Found)
15:26:05.828 [main] ERROR c.a.q.s.UITest - [2021-10-27T13:26:05.613Z] [SEVERE] http://192.168.43.29:5502/tools/tsdk/handlebars.min.js - Failed to load resource: the server responded with a status of 404 (Not Found)
15:26:05.828 [main] ERROR c.a.q.s.UITest - [2021-10-27T13:26:05.614Z] [SEVERE] http://192.168.43.29:5502/tools/db/personalization/clientlib/backbone.min.js - Failed to load resource: the server responded with a status of 404 (Not Found)
15:26:05.828 [main] ERROR c.a.q.s.UITest - [2021-10-27T13:26:05.615Z] [SEVERE] http://192.168.43.29:5502/libs/db/gui/components/authoring/editors/clientlibs/sites/page.min.js - Failed to load resource: the server responded with a status of 404 (Not Found)
15:26:05.828 [main] ERROR c.a.q.s.UITest - [2021-10-27T13:26:05.615Z] [SEVERE] http://192.168.43.29:5502/libs/db/gui/components/authoring/dialog/clientlibs/all.min.js - Failed to load resource: the server responded with a status of 404 (Not Found)
15:26:05.828 [main] ERROR c.a.q.s.UITest - [2021-10-27T13:26:05.621Z] [SEVERE] http://192.168.43.29:5502/tools/clientlibs/grommit/Crabui2/optional/imageeditor.min.js - Failed to load resource: the server responded with a status of 404 (Not Found)
15:26:05.828 [main] ERROR c.a.q.s.UITest - [2021-10-27T13:26:05.626Z] [SEVERE] http://192.168.43.29:5502/libs/clientlibs/grommit/richtext.min.js - Failed to load resource: the server responded with a status of 404 (Not Found)
15:26:05.828 [main] ERROR c.a.q.s.UITest - [2021-10-27T13:26:05.631Z] [SEVERE] http://192.168.43.29:5502/tools/clientlibs/grommit/lawnchair.min.js - Failed to load resource: the server responded with a status of 404 (Not Found)
15:26:05.828 [main] ERROR c.a.q.s.UITest - [2021-10-27T13:26:05.637Z] [SEVERE] http://192.168.43.29:5502/tools/foundation/clientlibs/jquery.min.js - Failed to load resource: the server responded with a status of 404 (Not Found)
15:26:05.828 [main] ERROR c.a.q.s.UITest - [2021-10-27T13:26:05.641Z] [SEVERE] http://192.168.43.29:5502/tools/foundation/clientlibs/shared.min.js - Failed to load resource: the server responded with a status of 404 (Not Found)
15:26:05.828 [main] ERROR c.a.q.s.UITest - [2021-10-27T13:26:05.646Z] [SEVERE] http://192.168.43.29:5502/libs/db/gui/components/authoring/editors/clientlibs/utils.min.js - Failed to load resource: the server responded with a status of 404 (Not Found)
15:26:05.828 [main] ERROR c.a.q.s.UITest - [2021-10-27T13:26:05.650Z] [SEVERE] http://192.168.43.29:5502/libs/db/gui/components/authoring/editors/clientlibs/core.min.js - Failed to load resource: the server responded with a status of 404 (Not Found)
15:26:05.828 [main] ERROR c.a.q.s.UITest - [2021-10-27T13:26:05.653Z] [SEVERE] http://192.168.43.29:5502/libs/grommit/ui/clientlibs/annotations.min.js - Failed to load resource: the server responded with a status of 404 (Not Found)
15:26:05.828 [main] ERROR c.a.q.s.UITest - [2021-10-27T13:26:05.657Z] [SEVERE] http://192.168.43.29:5502/libs/db/ups/rte/plugin.min.js - Failed to load resource: the server responded with a status of 404 (Not Found)
15:26:05.828 [main] ERROR c.a.q.s.UITest - [2021-10-27T13:26:05.661Z] [SEVERE] http://192.168.43.29:5502/libs/db/gui/components/authoring/searchfield/clientlibs/searchfield.min.js - Failed to load resource: the server responded with a status of 404 (Not Found)
15:26:05.828 [main] ERROR c.a.q.s.UITest - [2021-10-27T13:26:05.665Z] [SEVERE] http://192.168.43.29:5502/libs/db/contentinsight/clientlibs/editor.min.js - Failed to load resource: the server responded with a status of 404 (Not Found)
15:26:05.828 [main] ERROR c.a.q.s.UITest - [2021-10-27T13:26:05.668Z] [SEVERE] http://192.168.43.29:5502/tools/tsdk/handlebars.min.js - Failed to load resource: the server responded with a status of 404 (Not Found)
15:26:05.828 [main] ERROR c.a.q.s.UITest - [2021-10-27T13:26:05.672Z] [SEVERE] http://192.168.43.29:5502/tools/db/personalization/clientlib/underscore.min.js - Failed to load resource: the server responded with a status of 404 (Not Found)
15:26:05.828 [main] ERROR c.a.q.s.UITest - [2021-10-27T13:26:05.675Z] [SEVERE] http://192.168.43.29:5502/tools/db/personalization/clientlib/backbone.min.js - Failed to load resource: the server responded with a status of 404 (Not Found)
15:26:05.828 [main] ERROR c.a.q.s.UITest - [2021-10-27T13:26:05.679Z] [SEVERE] http://192.168.43.29:5502/libs/db/gui/components/authoring/editors/clientlibs/sites/page.min.js - Failed to load resource: the server responded with a status of 404 (Not Found)
15:26:05.828 [main] ERROR c.a.q.s.UITest - [2021-10-27T13:26:05.682Z] [SEVERE] http://192.168.43.29:5502/libs/db/gui/components/authoring/dialog/clientlibs/all.min.js - Failed to load resource: the server responded with a status of 404 (Not Found)
15:26:05.828 [main] ERROR c.a.q.s.UITest - [2021-10-27T13:26:05.684Z] [SEVERE] http://192.168.43.29:5502/editor.html/content/some/page.html 466:27 Uncaught TypeError: Cannot read properties of undefined (reading 'Manager')
15:26:05.828 [main] ERROR c.a.q.s.UITest - =======================================================
15:26:05.885 [main] INFO  i.g.b.w.d.DockerService - Stopping Docker container selenoid/vnc:chrome_95.0
**Error trace**: No error it simply hang
**Thread dump**:
"main" #1 prio=5 os_prio=31 cpu=2693.71ms elapsed=27.41s tid=0x00007fabe3809000 nid=0x2703 runnable  [0x000070000f5a6000]
   java.lang.Thread.State: RUNNABLE
	at com.github.dockerjava.transport.DomainSocket.read(Native Method)
	at com.github.dockerjava.transport.DomainSocket.read(DomainSocket.java:79)
	at com.github.dockerjava.transport.DomainSocket.access$200(DomainSocket.java:35)
	at com.github.dockerjava.transport.DomainSocket$DomainSocketInputStream.read(DomainSocket.java:164)
	at org.apache.hc.core5.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:149)
	at org.apache.hc.core5.http.impl.io.BHttpConnectionBase.fillInputBuffer(BHttpConnectionBase.java:265)
	at org.apache.hc.core5.http.impl.io.BHttpConnectionBase.isStale(BHttpConnectionBase.java:295)
	at org.apache.hc.core5.http.impl.io.DefaultBHttpClientConnection.isStale(DefaultBHttpClientConnection.java:67)
	at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager$1.get(PoolingHttpClientConnectionManager.java:287)
	- locked <0x000000061f37b6b0> (a org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager$1)
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.acquireEndpoint(InternalExecRuntime.java:109)
	at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:119)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:175)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:133)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:67)
	at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl.execute(ApacheDockerHttpClientImpl.java:183)
	at com.github.dockerjava.httpclient5.ApacheDockerHttpClient.execute(ApacheDockerHttpClient.java:9)
	at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:228)
	at com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:102)
	at com.github.dockerjava.core.exec.StopContainerCmdExec.execute(StopContainerCmdExec.java:33)
	at com.github.dockerjava.core.exec.StopContainerCmdExec.execute(StopContainerCmdExec.java:13)
	at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at com.github.dockerjava.core.command.StopContainerCmdImpl.exec(StopContainerCmdImpl.java:63)
	at io.github.bonigarcia.wdm.docker.DockerService.stopContainer(DockerService.java:326)
	- locked <0x0000000602f1c520> (a io.github.bonigarcia.wdm.docker.DockerService)
	at io.github.bonigarcia.wdm.docker.DockerService.stopAndRemoveContainer(DockerService.java:309)
	- locked <0x0000000602f1c520> (a io.github.bonigarcia.wdm.docker.DockerService)
	at io.github.bonigarcia.wdm.WebDriverManager$$Lambda$863/0x00000008007ccc40.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(java.base@11.0.8/ArrayList.java:1655)
	at java.util.stream.ReferencePipeline$Head.forEach(java.base@11.0.8/ReferencePipeline.java:658)
	at io.github.bonigarcia.wdm.WebDriverManager.quit(WebDriverManager.java:804)
	- locked <0x0000000602e089e0> (a io.github.bonigarcia.wdm.managers.ChromeDriverManager)
	at io.github.bonigarcia.wdm.WebDriverManager$$Lambda$862/0x00000008007cc840.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(java.base@11.0.8/Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(java.base@11.0.8/ReferencePipeline.java:658)
	at io.github.bonigarcia.wdm.WebDriverManager.quit(WebDriverManager.java:749)
	- locked <0x0000000602e089e0> (a io.github.bonigarcia.wdm.managers.ChromeDriverManager)
	at io.github.bonigarcia.seljup.SeleniumJupiter.lambda$quitWebDriver$4(SeleniumJupiter.java:579)
	at io.github.bonigarcia.seljup.SeleniumJupiter$$Lambda$861/0x00000008007cc440.accept(Unknown Source)
	at java.util.ArrayList.forEach(java.base@11.0.8/ArrayList.java:1541)
	at io.github.bonigarcia.seljup.SeleniumJupiter.quitWebDriver(SeleniumJupiter.java:567)
	at io.github.bonigarcia.seljup.SeleniumJupiter.afterEach(SeleniumJupiter.java:340)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAfterEachCallbacks$11(TestMethodTestDescriptor.java:255)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor$$Lambda$860/0x00000008007cc040.invoke(Unknown Source)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$12(TestMethodTestDescriptor.java:271)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor$$Lambda$832/0x00000008007a0c40.execute(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$13(TestMethodTestDescriptor.java:271)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor$$Lambda$831/0x00000008007a0840.accept(Unknown Source)
	at java.util.ArrayList.forEach(java.base@11.0.8/ArrayList.java:1541)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAllAfterMethodsOrCallbacks(TestMethodTestDescriptor.java:270)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAfterEachCallbacks(TestMethodTestDescriptor.java:254)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:143)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$225/0x000000080014dc40.execute(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$224/0x000000080014d840.invoke(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$223/0x000000080014d440.execute(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService$$Lambda$229/0x000000080014fc40.accept(Unknown Source)
	at java.util.ArrayList.forEach(java.base@11.0.8/ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$225/0x000000080014dc40.execute(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$224/0x000000080014d840.invoke(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$223/0x000000080014d440.execute(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService$$Lambda$229/0x000000080014fc40.accept(Unknown Source)
	at java.util.ArrayList.forEach(java.base@11.0.8/ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$225/0x000000080014dc40.execute(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$224/0x000000080014d840.invoke(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$223/0x000000080014d440.execute(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher$$Lambda$178/0x0000000800139040.accept(Unknown Source)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

**Comment by bonigarcia** [comment]
This should be fixed in Selenium-Jupiter 4.1.0, just released.
