### ISSUE TITLE
An error occurred for Firefox with SeleniumJupiter 4.0.1

### ISSUE THREAD

**Issue by pete2121** [bonigarcia/selenium-jupiter#201]
Hello,
When running Selenium-Jupiter 4.0.1 with Selenium-Java 4.0.0, after doing this:
 void testWithChromeAndFirefox(ChromeDriver driver1, FirefoxDriver driver2) 

- Chrome: starts properly
- Firefox: An error occurred: java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.firefox.FirefoxDriver.get(String)" because "firefox" is null
at io.github.peteplako.SeleniumLocalWebDriverTest.testWithFirefox(SeleniumLocalWebDriverTest.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)

**Comment by bonigarcia** [comment]
I experienced random problems with Firefox, and the underlying cause seems to be the driver (i.e., geckodriver) and not Selenium-Jupiter. In any case, you are not providing enough information to trace the problem. I'm closing this issue since it is incomplete (please follow the issue template next time).
