### ISSUE TITLE
Using host as docker network

### ISSUE THREAD

**Issue by ihusejnovic** [bonigarcia/selenium-jupiter#28]
Hi,
First of all, thanks for a great piece of software. :) 

I'm having issue with running tests when I set parameter sel.jup.docker.network=host.
Here is the stacktrace:

`13:19:22.840 [main] ERROR io.github.bonigarcia.handler.DockerDriverHandler - Exception resolving driver in Docker (CHROME latest)
io.github.bonigarcia.SeleniumJupiterException: Port 4444/tcp is not bindable in container aerokube/selenoid:1.6.2
	at io.github.bonigarcia.DockerService.getBindPort(DockerService.java:146)
	at io.github.bonigarcia.handler.DockerDriverHandler.startSelenoidContainer(DockerDriverHandler.java:551)
	at io.github.bonigarcia.handler.DockerDriverHandler.startDockerBrowser(DockerDriverHandler.java:480)
	at io.github.bonigarcia.handler.DockerDriverHandler.getDriverForBrowser(DockerDriverHandler.java:192)
	at io.github.bonigarcia.handler.DockerDriverHandler.resolve(DockerDriverHandler.java:156)
	at io.github.bonigarcia.handler.DockerDriverHandler.resolve(DockerDriverHandler.java:138)
	at io.github.bonigarcia.handler.RemoteDriverHandler.resolve(RemoteDriverHandler.java:81)
	at io.github.bonigarcia.SeleniumExtension.resolveParameter(SeleniumExtension.java:201)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.resolveParameter(ExecutableInvoker.java:207)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.resolveParameters(ExecutableInvoker.java:174)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.resolveParameters(ExecutableInvoker.java:135)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:116)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:170)
	at org.junit.jupiter.engine.execution.ThrowableCollector.execute(ThrowableCollector.java:40)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:166)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:113)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:58)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:112)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$2(HierarchicalTestExecutor.java:120)`

Do you have any clue how to resolve this?

**Comment by bonigarcia** [comment]
The `host` network mode is not valid for Selenium-Jupiter. In this type of network, containers are standalone and ports are not bindables. The containers started by Selenium-Jupiter (Selenoid and browser) need communication between them, and for that reason you get that error when configuring the network as `host`.

If your use case is testing the localhost, take a look to this part of the [documentation](https://bonigarcia.github.io/selenium-jupiter/#testing-localhost).
