### ISSUE TITLE
NoClassDefFoundError in 4.3.3

### ISSUE THREAD

**Issue by jendap** [bonigarcia/selenium-jupiter#347]
The latest version (4.3.3) seems to have some classpath issues:

1) First issue is:

Caused by: java.lang.NoClassDefFoundError: org/apache/hc/client5/http/config/ConnectionConfig
	at io.github.bonigarcia.wdm.online.HttpClient.<init>(HttpClient.java:121)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:405)

It looks like ConnectionConfig is _not_ on 5.1.x branch but selenium-jupiter references 5.1.4

2) After explicit dependency on newer httpclient5 5.2.1 there is another error:

Caused by: java.lang.NoClassDefFoundError: io/opentelemetry/sdk/autoconfigure/spi/internal/DefaultConfigProperties
	at io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdkBuilder.computeConfigProperties(AutoConfiguredOpenTelemetrySdkBuilder.java:428)
	at io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdkBuilder.getConfig(AutoConfiguredOpenTelemetrySdkBuilder.java:422)
	at io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdkBuilder.build(AutoConfiguredOpenTelemetrySdkBuilder.java:329)
	at org.openqa.selenium.remote.tracing.opentelemetry.OpenTelemetryTracer.createTracer(OpenTelemetryTracer.java:81)
	at org.openqa.selenium.remote.tracing.opentelemetry.OpenTelemetryTracer.getInstance(OpenTelemetryTracer.java:60)
	at org.openqa.selenium.remote.RemoteWebDriver.createExecutor(RemoteWebDriver.java:180)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:139)
	at io.github.bonigarcia.wdm.webdriver.WebDriverCreator.createRemoteWebDriver(WebDriverCreator.java:89)

It looks like the tracing is in selenium itself and selenium brings in bunch of opentracing jar files on class path. But obviously not enough classes. Would it make sense to just disable the tracing? How about adding the third parameter (enableTracing=false) in io.github.bonigarcia.wdm.webdriver.WebDriverCreator.createRemoteWebDriver(WebDriverCreator.java:89)?

**Comment by bonigarcia** [comment]
This seems to be a dependencies problem in your project. Maybe some of your dependencies is changing the versions of the Apache HTTP Client, which is causing the issue. 

See, for example, this [example repo](https://github.com/bonigarcia/selenium-jupiter-examples). It uses the latest versions of Selenium-Jupiter and Selenium, and tests are being executed properly both with Maven and Gradle, without dependencies problems (see this [job](https://github.com/bonigarcia/selenium-jupiter-examples/actions/runs/4383707679), executed right now).
