### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by bstobbe** [bonigarcia/selenium-jupiter#60]
We're behind a corporate firewall and have to use a proxy for internet access. When using selenium-jupiter, the WebDriverManager cannot find the webdrivers. Is there a way to configure the use of a proxy for the WebDriverManager?

`08:29:23.053 [main] DEBUG io.github.bonigarcia.wdm.WebDriverManager - The proper geckodriver version for your Mozilla Firefox is unknown ... trying with the latest
08:29:23.072 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Reading https://api.github.com/repos/mozilla/geckodriver/releases to seek geckodriver
08:29:23.136 [main] WARN io.github.bonigarcia.wdm.WebDriverManager - There was an error managing geckodriver (latest version) (api.github.com) ... trying again using cache and mirror
08:29:23.339 [main] DEBUG io.github.bonigarcia.wdm.WebDriverManager - The proper geckodriver version for your Mozilla Firefox is unknown ... trying with the latest
08:29:23.370 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Reading http://npm.taobao.org/mirrors/geckodriver to seek geckodriver
08:29:23.370 [main] ERROR io.github.bonigarcia.wdm.WebDriverManager - There was an error managing geckodriver (latest version) (npm.taobao.org)`

**Comment by bonigarcia** [comment]
WebDriverManager Proxy can be configured as usual when used in Selenium-Jupiter, for example:

```
@ExtendWith(SeleniumExtension.class)
public class ConfigWdmJupiterTest {

    @BeforeAll
    static void setup() {
        WebDriverManager.globalConfig().setProxy("...");
        WebDriverManager.globalConfig().setProxyUser("...");
        WebDriverManager.globalConfig().setProxyPass("...");
    }

    @Test
    void myTest(ChromeDriver chrome, FirefoxDriver firefox) {
        // ...
    }

}
```

**Comment by MichielBugherJelli** [comment]
@bonigarcia is there also a way to set this using configuration files?
I have been looking for a way to do it, but have not found it.
I'm hoping there is something in selenium-jupiter.properties or browsers.json to accomplish this.

**Comment by bstobbe** [comment]
The problem for me is that our dns server seems to be behind the proxy so the dns lookup doesn't work

```
09:48:17.036 [main] ERROR io.github.bonigarcia.wdm.WebDriverManager - There was an error managing geckodriver (latest version) (npm.taobao.org)
java.net.UnknownHostException: npm.taobao.org
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at io.github.bonigarcia.wdm.HttpClient.execute(HttpClient.java:169)
	[...]
```
