### ISSUE TITLE
chrome vnc versions 82.0 and 83.0 cause error

### ISSUE THREAD

**Issue by stevej2** [bonigarcia/selenium-jupiter#87]
**Description of the problem**: With no other changes, specifying versions 82.0 or 83.0 of the vnc chrome image, results in an error. version 81.0 and 84.0 85.0 work without error.

**Browser and version**: Chrome in Docker with vnc 83.0

**Operating system**: OSX Catalina

**Selenium-Jupiter version**: latest

**Selenium-Jupiter use**: @Test
    public void testDockerChromeSelenide(
            @DockerBrowser(type = CHROME, version = "84.0") SelenideDriver driver) {

**Selenium-Jupiter traces**: ######### Starting test testDockerChromeSelenide(SelenideDriver) #########

09:49:47.023 [ForkJoinPool-1-worker-51] DEBUG com.spotify.docker.client.DockerCertificates - /Users/stephenjohnston/.docker/ca.pem, /Users/stephenjohnston/.docker/key.pem or /Users/stephenjohnston/.docker/cert.pem does not exist, not using SSL
09:49:47.133 [ForkJoinPool-1-worker-51] DEBUG com.spotify.docker.client.DockerConfigReader - Using configfile: /Users/stephenjohnston/.docker/config.json
09:49:47.242 [ForkJoinPool-1-worker-51] INFO io.github.bonigarcia.seljup.handler.DockerDriverHandler - Using CHROME version 83.0
09:49:47.299 [ForkJoinPool-1-worker-51] INFO io.github.bonigarcia.seljup.DockerService - Starting Docker container aerokube/selenoid:1.10.0
09:49:47.393 [ForkJoinPool-1-worker-51] DEBUG com.spotify.docker.client.DefaultDockerClient - Creating container with ContainerConfig: ContainerConfig{hostname=null, domainname=null, user=null, attachStdin=null, attachStdout=null, attachStderr=null, portSpecs=null, exposedPorts=[4444], tty=null, openStdin=null, stdinOnce=null, env=[DOCKER_API_VERSION=1.35, TZ=Europe/London, LANG=en, ENABLE_WINDOW_MANAGER=true], cmd=[sh, -c, mkdir -p /etc/selenoid/; echo '{"chrome":{"default":"83.0","versions":{"83.0":{"image":"selenoid/vnc:chrome_83.0","port":"4444","path":"/","tmpfs":{"/tmp":"size=128m"},"env":["DOCKER_API_VERSION=1.35","TZ=Europe/London","LANG=en","ENABLE_WINDOW_MANAGER=true"],"volumes":[]}}}}' > /etc/selenoid/browsers.json; /usr/bin/selenoid -listen :4444 -service-startup-timeout 3m -conf /etc/selenoid/browsers.json -video-output-dir /opt/selenoid/video/ -timeout 1m0s -container-network bridge -limit 9], image=aerokube/selenoid:1.10.0, volumes=[], workingDir=null, entrypoint=[], networkDisabled=null, onBuild=null, labels=null, macAddress=null, hostConfig=HostConfig{binds=[/var/run/docker.sock:/var/run/docker.sock], blkioWeight=null, blkioWeightDevice=null, blkioDeviceReadBps=null, blkioDeviceWriteBps=null, blkioDeviceReadIOps=null, blkioDeviceWriteIOps=null, containerIdFile=null, lxcConf=null, privileged=null, portBindings={4444=[PortBinding{hostIp=0.0.0.0, hostPort=}]}, links=null, publishAllPorts=null, dns=null, dnsOptions=null, dnsSearch=null, extraHosts=null, groupAdd=null, volumesFrom=null, capAdd=null, capDrop=null, networkMode=bridge, securityOpt=null, devices=null, memory=null, memorySwap=null, kernelMemory=null, memorySwappiness=null, memoryReservation=null, nanoCpus=null, cpuPeriod=null, cpuShares=null, cpusetCpus=null, cpusetMems=null, cpuQuota=null, cgroupParent=null, restartPolicy=null, logConfig=null, ipcMode=null, ulimits=null, pidMode=null, shmSize=null, oomKillDisable=null, oomScoreAdj=null, autoRemove=null, pidsLimit=null, tmpfs=null, readonlyRootfs=null, storageOpt=null, runtime=null}, stopSignal=null, healthcheck=null, networkingConfig=null}
[DEBUG RequestAddCookies] CookieSpec selected: default
[DEBUG RequestAuthCache] Auth cache not set in the context
[DEBUG PoolingHttpClientConnectionManager] Connection request: [route: {}->unix://localhost:80][total available: 0; route allocated: 0 of 100; total allocated: 0 of 100]
[DEBUG PoolingHttpClientConnectionManager] Connection leased: [id: 0][route: {}->unix://localhost:80][total available: 0; route allocated: 1 of 100; total allocated: 1 of 100]
[DEBUG MainClientExec] Opening connection {}->unix://localhost:80
[DEBUG DefaultHttpClientConnectionOperator] Connecting to localhost/127.0.0.1:80
[DEBUG DefaultHttpClientConnectionOperator] Connection established [family=PF_UNIX path=]<->[family=PF_UNIX path=/var/run/docker.sock]
[DEBUG LoggingManagedHttpClientConnection] http-outgoing-0: set socket timeout to 30000
[DEBUG MainClientExec] Executing request POST /containers/create HTTP/1.1
[DEBUG MainClientExec] Target auth state: UNCHALLENGED
[DEBUG MainClientExec] Proxy auth state: UNCHALLENGED
[DEBUG LoggingManagedHttpClientConnection] http-outgoing-0 >> POST /containers/create HTTP/1.1
[DEBUG LoggingManagedHttpClientConnection] http-outgoing-0 >> Accept: application/json
[DEBUG LoggingManagedHttpClientConnection] http-outgoing-0 >> Content-Type: application/json
[DEBUG LoggingManagedHttpClientConnection] http-outgoing-0 >> User-Agent: Jersey/2.22.2 (Apache HttpClient 4.5.12)
[DEBUG LoggingManagedHttpClientConnection] http-outgoing-0 >> Transfer-Encoding: chunked
[DEBUG LoggingManagedHttpClientConnection] http-outgoing-0 >> Host: localhost:80
[DEBUG LoggingManagedHttpClientConnection] http-outgoing-0 >> Connection: Keep-Alive
[DEBUG LoggingManagedHttpClientConnection] http-outgoing-0 >> Accept-Encoding: gzip,deflate
[DEBUG Wire] http-outgoing-0 >> "POST /containers/create HTTP/1.1[\r][\n]"
[DEBUG Wire] http-outgoing-0 >> "Accept: application/json[\r][\n]"
[DEBUG Wire] http-outgoing-0 >> "Content-Type: application/json[\r][\n]"
[DEBUG Wire] http-outgoing-0 >> "User-Agent: Jersey/2.22.2 (Apache HttpClient 4.5.12)[\r][\n]"
[DEBUG Wire] http-outgoing-0 >> "Transfer-Encoding: chunked[\r][\n]"
[DEBUG Wire] http-outgoing-0 >> "Host: localhost:80[\r][\n]"
[DEBUG Wire] http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
[DEBUG Wire] http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
[DEBUG Wire] http-outgoing-0 >> "[\r][\n]"
[DEBUG Wire] http-outgoing-0 >> "1b[\r][\n]"
[DEBUG Wire] http-outgoing-0 >> "{"ExposedPorts":{"4444":{}}[\r][\n]"
[DEBUG Wire] http-outgoing-0 >> "2b3[\r][\n]"
[DEBUG Wire] http-outgoing-0 >> ","Env":["DOCKER_API_VERSION=1.35","TZ=Europe/London","LANG=en","ENABLE_WINDOW_MANAGER=true"],"Cmd":["sh","-c","mkdir -p /etc/selenoid/; echo '{\"chrome\":{\"default\":\"83.0\",\"versions\":{\"83.0\":{\"image\":\"selenoid/vnc:chrome_83.0\",\"port\":\"4444\",\"path\":\"/\",\"tmpfs\":{\"/tmp\":\"size=128m\"},\"env\":[\"DOCKER_API_VERSION=1.35\",\"TZ=Europe/London\",\"LANG=en\",\"ENABLE_WINDOW_MANAGER=true\"],\"volumes\":[]}}}}' > /etc/selenoid/browsers.json; /usr/bin/selenoid -listen :4444 -service-startup-timeout 3m -conf /etc/selenoid/browsers.json -video-output-dir /opt/selenoid/video/ -timeout 1m0s -container-network bridge -limit 9"],"Image":"aerokube/selenoid:1.10.0","Volumes":{}[\r][\n]"
[DEBUG Wire] http-outgoing-0 >> "ac[\r][\n]"
[DEBUG Wire] http-outgoing-0 >> ","Entrypoint":[""],"HostConfig":{"Binds":["/var/run/docker.sock:/var/run/docker.sock"],"PortBindings":{"4444":[{"HostIp":"0.0.0.0","HostPort":""}]},"NetworkMode":"bridge"}}[\r][\n]"
[DEBUG Wire] http-outgoing-0 >> "0[\r][\n]"
[DEBUG Wire] http-outgoing-0 >> "[\r][\n]"
[DEBUG Wire] http-outgoing-0 << "HTTP/1.1 404 Not Found[\r][\n]"
[DEBUG Wire] http-outgoing-0 << "Api-Version: 1.40[\r][\n]"
[DEBUG Wire] http-outgoing-0 << "Content-Length: 54[\r][\n]"
[DEBUG Wire] http-outgoing-0 << "Content-Type: application/json[\r][\n]"
[DEBUG Wire] http-outgoing-0 << "Date: Wed, 30 Sep 2020 08:49:47 GMT[\r][\n]"
[DEBUG Wire] http-outgoing-0 << "Docker-Experimental: false[\r][\n]"
[DEBUG Wire] http-outgoing-0 << "Ostype: linux[\r][\n]"
[DEBUG Wire] http-outgoing-0 << "Server: Docker/19.03.12 (linux)[\r][\n]"
[DEBUG Wire] http-outgoing-0 << "[\r][\n]"
[DEBUG LoggingManagedHttpClientConnection] http-outgoing-0 << HTTP/1.1 404 Not Found
[DEBUG LoggingManagedHttpClientConnection] http-outgoing-0 << Api-Version: 1.40
[DEBUG LoggingManagedHttpClientConnection] http-outgoing-0 << Content-Length: 54
[DEBUG LoggingManagedHttpClientConnection] http-outgoing-0 << Content-Type: application/json
[DEBUG LoggingManagedHttpClientConnection] http-outgoing-0 << Date: Wed, 30 Sep 2020 08:49:47 GMT
[DEBUG LoggingManagedHttpClientConnection] http-outgoing-0 << Docker-Experimental: false
[DEBUG LoggingManagedHttpClientConnection] http-outgoing-0 << Ostype: linux
[DEBUG LoggingManagedHttpClientConnection] http-outgoing-0 << Server: Docker/19.03.12 (linux)
[DEBUG MainClientExec] Connection can be kept alive indefinitely
[DEBUG Wire] http-outgoing-0 << "{"message":"No such image: aerokube/selenoid:1.10.0"}[\n]"
[DEBUG PoolingHttpClientConnectionManager] Connection [id: 0][route: {}->unix://localhost:80] can be kept alive indefinitely
[DEBUG LoggingManagedHttpClientConnection] http-outgoing-0: set socket timeout to 0
[DEBUG PoolingHttpClientConnectionManager] Connection released: [id: 0][route: {}->unix://localhost:80][total available: 1; route allocated: 1 of 100; total allocated: 1 of 100]
09:49:47.927 [pool-3-thread-1] INFO io.github.bonigarcia.seljup.DockerService - Stopping Docker container aerokube/selenoid:1.10.0
09:49:47.929 [pool-3-thread-1] WARN io.github.bonigarcia.seljup.DockerService - Exception stopping container aerokube/selenoid:1.10.0
java.lang.NullPointerException: path is 'null'.
	at jersey.repackaged.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:226)
	at org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:151)
	at org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:59)
	at com.spotify.docker.client.DefaultDockerClient.stopContainer(DefaultDockerClient.java:855)
	at io.github.bonigarcia.seljup.DockerService.stopContainer(DockerService.java:260)
	at io.github.bonigarcia.seljup.DockerService.stopAndRemoveContainer(DockerService.java:244)
	at io.github.bonigarcia.seljup.handler.DockerDriverHandler.lambda$stopContainers$0(DockerDriverHandler.java:583)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
[ INFO TestListener] ######### Test Execution Finished: testDockerChromeSelenide(SelenideDriver) FAILED #########

**Error trace**: org.junit.jupiter.api.extension.ParameterResolutionException: Failed to resolve parameter [com.codeborne.selenide.SelenideDriver arg0] in method [public void Framework_Tests_UI.testDockerChromeSelenide(com.codeborne.selenide.SelenideDriver)]: io.github.bonigarcia.seljup.SeleniumJupiterException: Exception resolving driver in Docker (CHROME 83.0)

	at org.junit.jupiter.engine.execution.ExecutableInvoker.resolveParameter(ExecutableInvoker.java:239)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.resolveParameters(ExecutableInvoker.java:183)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.resolveParameters(ExecutableInvoker.java:144)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:96)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:129)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:129)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: io.github.bonigarcia.seljup.SeleniumJupiterException: io.github.bonigarcia.seljup.SeleniumJupiterException: Exception resolving driver in Docker (CHROME 83.0)
	at io.github.bonigarcia.seljup.handler.DriverHandler.handleException(DriverHandler.java:104)
	at io.github.bonigarcia.seljup.handler.SelenideDriverHandler.resolve(SelenideDriverHandler.java:100)
	at io.github.bonigarcia.seljup.SeleniumExtension.resolveHandler(SeleniumExtension.java:310)
	at io.github.bonigarcia.seljup.SeleniumExtension.resolveParameter(SeleniumExtension.java:223)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.resolveParameter(ExecutableInvoker.java:216)
	... 43 more
Caused by: io.github.bonigarcia.seljup.SeleniumJupiterException: Exception resolving driver in Docker (CHROME 83.0)
	at io.github.bonigarcia.seljup.handler.DockerDriverHandler.resolve(DockerDriverHandler.java:220)
	at io.github.bonigarcia.seljup.handler.DockerDriverHandler.resolve(DockerDriverHandler.java:189)
	at io.github.bonigarcia.seljup.handler.SelenideDriverHandler.resolve(SelenideDriverHandler.java:73)
	... 46 more
Caused by: com.spotify.docker.client.exceptions.ImageNotFoundException: Image not found: aerokube/selenoid:1.10.0
	at com.spotify.docker.client.DefaultDockerClient.createContainer(DefaultDockerClient.java:747)
	at com.spotify.docker.client.DefaultDockerClient.createContainer(DefaultDockerClient.java:724)
	at io.github.bonigarcia.seljup.DockerService.startContainer(DockerService.java:164)
	at io.github.bonigarcia.seljup.handler.DockerDriverHandler.startSelenoidContainer(DockerDriverHandler.java:810)
	at io.github.bonigarcia.seljup.handler.DockerDriverHandler.startDockerBrowser(DockerDriverHandler.java:732)
	at io.github.bonigarcia.seljup.handler.DockerDriverHandler.setHubUrl(DockerDriverHandler.java:334)
	at io.github.bonigarcia.seljup.handler.DockerDriverHandler.getDriverForBrowser(DockerDriverHandler.java:274)
	at io.github.bonigarcia.seljup.handler.DockerDriverHandler.resolve(DockerDriverHandler.java:211)
	... 48 more
Caused by: com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST unix://localhost:80/containers/create: 404, body: {"message":"No such image: aerokube/selenoid:1.10.0"}

	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2840)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2723)
	at com.spotify.docker.client.DefaultDockerClient.createContainer(DefaultDockerClient.java:742)
	... 55 more
Caused by: javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1008)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:816)
	at org.glassfish.jersey.client.JerseyInvocation.access$700(JerseyInvocation.java:92)
	at org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:773)
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:198)
	at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:79)
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:180)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:210)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by stevej2** [comment]
It seems to indicate it can't find the selenoid image, however just changing between version 83.0 and 84.0 changes from error to no error consistently.

**Comment by stevej2** [comment]
User error!
